### PR TITLE
Feature/configurable retry codes

### PR DESCRIPTION
**Pull request by sd-charris**

### CODE REVIEW

**Review by whedley — COMMENTED** [review]
I'm not sure you needed to go to all of the effort of making the retry codes configurable. Is there a good reason why we wouldn't want to add 502 to the default retry code list?

**Comment by sd-charris** [comment]
> I'm not sure you needed to go to all of the effort of making the retry codes configurable. Is there a good reason why we wouldn't want to add 502 to the default retry code list?

My only concern was changing behavior of a public facing sdk. If anyone actually uses it is another question...

**Comment by whedley** [comment]
It's either going to succeed where it previously failed, or fail slower. I don't think anyone would mind. Let's just update the defaults.

**Review by whedley — APPROVED** [review]
TLTQ

**Pull request merged**
